# Form implementation generated from reading ui file 'c:\Users\Tech Brand Store\Desktop\breeha db\Database Project\GUI_Elements\Add University Details (Register Now) - By Administrator.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 403)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    \n"
"    border-image: url(GUI_Elements/bg image.png);\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  background: transparent;\n"
"  color: rgb(86, 86, 86);\n"
"  border-bottom: 1px solid rgb(86, 86, 86);\n"
"}\n"
"\n"
"QPushButton {\n"
"  background-color: #85E3D9;\n"
"  color: #0f1925;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #85E3D9;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #85E3D9;\n"
"  border: 3px solid #85E3D9;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 551, 371))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 171, 20))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(86, 86, 86);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(140, 50, 131, 21))
        self.lineEdit.setStyleSheet("background:transparent;")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 101, 20))
        self.label_4.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 91, 20))
        self.label_5.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 80, 131, 21))
        self.lineEdit_5.setStyleSheet("background:transparent;")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 120, 91, 20))
        self.label_6.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 150, 121, 20))
        self.label_7.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 101, 20))
        self.label_8.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 200, 101, 20))
        self.label_9.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(30, 230, 101, 20))
        self.label_12.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_10.setEnabled(True)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 110, 131, 21))
        self.lineEdit_10.setStyleSheet("background:transparent;")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setPlaceholderText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(30, 260, 91, 20))
        self.label_10.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 91, 20))
        self.label_11.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(290, 50, 121, 20))
        self.label_13.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(290, 80, 121, 20))
        self.label_14.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_14.setObjectName("label_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_11.setEnabled(True)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 140, 131, 21))
        self.lineEdit_11.setStyleSheet("background:transparent;")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setPlaceholderText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_12.setEnabled(True)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 170, 131, 21))
        self.lineEdit_12.setStyleSheet("background:transparent;")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setPlaceholderText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_13.setEnabled(True)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 200, 131, 21))
        self.lineEdit_13.setStyleSheet("background:transparent;")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setPlaceholderText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_14.setEnabled(True)
        self.lineEdit_14.setGeometry(QtCore.QRect(140, 230, 131, 21))
        self.lineEdit_14.setStyleSheet("background:transparent;")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setPlaceholderText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_15.setEnabled(True)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 260, 131, 21))
        self.lineEdit_15.setStyleSheet("background:transparent;")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setPlaceholderText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_16.setEnabled(True)
        self.lineEdit_16.setGeometry(QtCore.QRect(140, 290, 131, 21))
        self.lineEdit_16.setStyleSheet("background:transparent;")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setPlaceholderText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_17.setEnabled(True)
        self.lineEdit_17.setGeometry(QtCore.QRect(380, 50, 131, 21))
        self.lineEdit_17.setStyleSheet("background:transparent;")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setPlaceholderText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_18.setEnabled(True)
        self.lineEdit_18.setGeometry(QtCore.QRect(380, 80, 131, 21))
        self.lineEdit_18.setStyleSheet("background:transparent;")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setPlaceholderText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 150, 351, 291))
        self.label_2.setStyleSheet("image: url(GUI_Elements/2.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 310, 161, 41))
        self.pushButton_2.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #85E3D9;\n"
"  border: 3px solid #85E3D9;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit University Details"))
        self.label_3.setText(_translate("MainWindow", "Add University Details"))
        self.label_4.setText(_translate("MainWindow", "University Name"))
        self.label_5.setText(_translate("MainWindow", "Location"))
        self.label_6.setText(_translate("MainWindow", "University Type"))
        self.label_7.setText(_translate("MainWindow", "Entry Test Type"))
        self.label_8.setText(_translate("MainWindow", "Acceptance Rate (%)"))
        self.label_9.setText(_translate("MainWindow", "SAT Score Required"))
        self.label_12.setText(_translate("MainWindow", "Average Annual Cost"))
        self.label_10.setText(_translate("MainWindow", "Program 1"))
        self.label_11.setText(_translate("MainWindow", "Program 2"))
        self.label_13.setText(_translate("MainWindow", "Program 3"))
        self.label_14.setText(_translate("MainWindow", "Program 4"))
        self.pushButton_2.setText(_translate("MainWindow", "SUBMIT"))
