# Form implementation generated from reading ui file 'c:\Users\Tech Brand Store\Desktop\breeha db\Database Project\GUI_Elements\Student Login.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 391)
        MainWindow.setStyleSheet("QMainWindow { \n"
"    border-image: url(GUI_Elements/bg image.png);\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  background: transparent;\n"
"  color: rgb(86, 86, 86);\n"
"  border-bottom: 1px solid rgb(86, 86, 86);\n"
"}\n"
"\n"
"QPushButton {\n"
"  background-color: #00557f;\n"
"  color: #0f1925;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #00557f;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #85E3D9;\n"
"  border: 3px solid #85E3D9;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(310, 50, 241, 271))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 111, 16))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(86, 86, 86);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 100, 171, 21))
        self.lineEdit.setStyleSheet("background:transparent;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 150, 171, 21))
        self.lineEdit_2.setStyleSheet("background:transparent;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 121, 20))
        self.label_4.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 130, 121, 20))
        self.label_5.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 180, 121, 20))
        self.label_6.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(86, 86, 86);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 81, 41))
        self.pushButton.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #85E3D9;\n"
"  border: 3px solid #85E3D9;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 200, 81, 41))
        self.pushButton_2.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #85E3D9;\n"
"  border: 3px solid #85E3D9;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 50, 51, 51))
        self.label_8.setStyleSheet("\n"
"image: url(GUI_Elements/DB Project.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(470, 0, 181, 181))
        self.label_9.setStyleSheet("image: url(GUI_Elements/2.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-50, -10, 371, 301))
        self.label.setStyleSheet("image: url(GUI_Elements/5.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, 10, 351, 341))
        self.label_2.setStyleSheet("image: url(GUI_Elements/login.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "🔒Login Page"))
        self.label_3.setText(_translate("MainWindow", "Welcome Back"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " Enter your username/email"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "🔒 •••••••••••••"))
        self.label_4.setText(_translate("MainWindow", "Username/Email"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.label_6.setText(_translate("MainWindow", "Forgot Password?"))
        self.pushButton.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_2.setText(_translate("MainWindow", "SIGN UP"))
